apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql01-srv
spec:
  ports:
  - nodePort: 30011
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort
