apiVersion: v1
kind: Pod
metadata:
        name: mysql
        labels:
                app: mysql 
                type: backend
spec:
        containers:
        - name: mysql01
          image: mysql/mysql-server
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: mysql100
 
