apiVersion: v1
kind: Service
metadata:
  name: php-app-service-loadbalancer
spec:
  selector:
    app: php  # This should match the label of your PHP pod
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
  type: LoadBalancer